defaults:
  - model_checkpoint@val_loss:
      - model_checkpoint.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

val_loss:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:04d}_valloss_{val/loss:.4f}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1
